// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using rrhh_backend.Data;

#nullable disable

namespace rrhh_backend.Migrations
{
    [DbContext(typeof(RrHhContext))]
    partial class RrHhContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("rrhh_backend.Data.Models.AdminBitacoraUsuario", b =>
                {
                    b.Property<int>("IdBitacoraUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AccionBitacora")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("FechaBitacora")
                        .HasColumnType("datetime");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdBitacoraUser");

                    b.HasIndex(new[] { "IdUsuario" }, "IX_Relationship3");

                    b.ToTable("AdminBitacoraUsuario", (string)null);
                });

            modelBuilder.Entity("rrhh_backend.Data.Models.AdminEstado", b =>
                {
                    b.Property<int>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("longtext");

                    b.Property<string>("NombreEstado")
                        .IsRequired()
                        .HasMaxLength(55)
                        .IsUnicode(false)
                        .HasColumnType("varchar(55)");

                    b.HasKey("IdEstado");

                    b.ToTable("AdminEstado", (string)null);
                });

            modelBuilder.Entity("rrhh_backend.Data.Models.AdminPermiso", b =>
                {
                    b.Property<int>("IdPermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DescripcionPermiso")
                        .HasMaxLength(55)
                        .IsUnicode(false)
                        .HasColumnType("varchar(55)");

                    b.Property<string>("NombrePermiso")
                        .IsRequired()
                        .HasMaxLength(55)
                        .IsUnicode(false)
                        .HasColumnType("varchar(55)");

                    b.HasKey("IdPermiso");

                    b.ToTable("AdminPermisos", (string)null);
                });

            modelBuilder.Entity("rrhh_backend.Data.Models.AdminResetPassword", b =>
                {
                    b.Property<int>("IdToken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacionToken")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaExpiracionToken")
                        .HasColumnType("datetime");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("NombreToken")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("IdToken");

                    b.HasIndex(new[] { "IdUsuario" }, "IX_Relationship2");

                    b.ToTable("AdminResetPassword", (string)null);
                });

            modelBuilder.Entity("rrhh_backend.Data.Models.AdminRole", b =>
                {
                    b.Property<int>("IdRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DescripcionRol")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(55)
                        .IsUnicode(false)
                        .HasColumnType("varchar(55)");

                    b.HasKey("IdRole");

                    b.ToTable("AdminRoles", (string)null);
                });

            modelBuilder.Entity("rrhh_backend.Data.Models.AdminRolesPermiso", b =>
                {
                    b.Property<int>("IdRolePermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("IdPermiso")
                        .HasColumnType("int");

                    b.Property<int>("IdRole")
                        .HasColumnType("int");

                    b.HasKey("IdRolePermiso");

                    b.HasIndex(new[] { "IdRole" }, "IX_Relationship4");

                    b.HasIndex(new[] { "IdPermiso" }, "IX_Relationship5");

                    b.ToTable("AdminRolesPermisos", (string)null);
                });

            modelBuilder.Entity("rrhh_backend.Data.Models.AdminUser", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<int?>("IdColaborador")
                        .HasColumnType("int");

                    b.Property<int?>("IdEstado")
                        .HasColumnType("int");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(55)
                        .IsUnicode(false)
                        .HasColumnType("varchar(55)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(55)
                        .IsUnicode(false)
                        .HasColumnType("varchar(55)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdColaborador")
                        .IsUnique();

                    b.HasIndex(new[] { "IdEstado" }, "IX_Relationship1");

                    b.ToTable("AdminUser", (string)null);
                });

            modelBuilder.Entity("rrhh_backend.Data.Models.AdminUserRole", b =>
                {
                    b.Property<int>("IdUserRoles")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("datetime");

                    b.Property<int>("IdRole")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdUserRoles");

                    b.HasIndex(new[] { "IdUsuario" }, "IX_Relationship7");

                    b.HasIndex(new[] { "IdRole" }, "IX_Relationship8");

                    b.ToTable("AdminUserRoles", (string)null);
                });

            modelBuilder.Entity("rrhh_backend.Data.Models.RHColaborador", b =>
                {
                    b.Property<int>("IdColaborador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ApellidoCasada")
                        .HasColumnType("longtext");

                    b.Property<string>("Codigo")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Debaja")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DepartamentoExtendido")
                        .HasColumnType("longtext");

                    b.Property<string>("Direccion")
                        .HasColumnType("longtext");

                    b.Property<string>("Dpi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("FechaInicioLabores")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Foto")
                        .HasColumnType("longtext");

                    b.Property<int>("IdDepartamento")
                        .HasColumnType("int");

                    b.Property<int>("IdEstadoCivil")
                        .HasColumnType("int");

                    b.Property<int>("IdEstadoColaborador")
                        .HasColumnType("int");

                    b.Property<string>("LugarNacimiento")
                        .HasColumnType("longtext");

                    b.Property<string>("MunicipioExtendido")
                        .HasColumnType("longtext");

                    b.Property<string>("Nacionalidad")
                        .HasColumnType("longtext");

                    b.Property<string>("NoCuentaBancaria")
                        .HasColumnType("longtext");

                    b.Property<string>("NoIGSS")
                        .HasColumnType("longtext");

                    b.Property<string>("NoNIT")
                        .HasColumnType("longtext");

                    b.Property<string>("NombreConyuge")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SegundoApellido")
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .HasColumnType("longtext");

                    b.HasKey("IdColaborador");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_RHColaborador_Email");

                    b.HasIndex("IdDepartamento");

                    b.HasIndex("IdEstadoCivil");

                    b.HasIndex("IdEstadoColaborador");

                    b.ToTable("RHColaborador", (string)null);
                });

            modelBuilder.Entity("rrhh_backend.Data.Models.RHDepartamento", b =>
                {
                    b.Property<int>("IdDepartamentos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DescripcionDepartamento")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("longtext");

                    b.Property<string>("NombreDepartamento")
                        .IsRequired()
                        .HasMaxLength(55)
                        .IsUnicode(false)
                        .HasColumnType("longtext");

                    b.HasKey("IdDepartamentos");

                    b.ToTable("RHDepartamento", (string)null);
                });

            modelBuilder.Entity("rrhh_backend.Data.Models.RHEstadoCivil", b =>
                {
                    b.Property<int>("IdEstadoCivil")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("EstadoCivil")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdEstadoCivil");

                    b.ToTable("RHEstadoCivil", (string)null);
                });

            modelBuilder.Entity("rrhh_backend.Data.Models.RHEstadoColaborador", b =>
                {
                    b.Property<int>("IdEstadoColaborador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EstadosColaborador")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdEstadoColaborador");

                    b.ToTable("RHEstadoColaborador", (string)null);
                });

            modelBuilder.Entity("rrhh_backend.Data.Models.RHEstadoLicencias", b =>
                {
                    b.Property<int>("IdEstadoLicencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<string>("EstadoLicencia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdEstadoLicencia");

                    b.ToTable("RHEstadoLicencias", (string)null);
                });

            modelBuilder.Entity("rrhh_backend.Data.Models.RHHistorialDepartamento", b =>
                {
                    b.Property<int>("IdHistorialDepartamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdColaborador")
                        .HasColumnType("int");

                    b.Property<int>("IdDepartamento")
                        .HasColumnType("int");

                    b.HasKey("IdHistorialDepartamento");

                    b.HasIndex("IdColaborador");

                    b.HasIndex("IdDepartamento");

                    b.ToTable("RHHistorialDepartamento", (string)null);
                });

            modelBuilder.Entity("rrhh_backend.Data.Models.RHLicencias", b =>
                {
                    b.Property<int>("IdLicencias")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdColaborador")
                        .HasColumnType("int");

                    b.Property<int>("IdEstadoLicencia")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoLicencia")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasColumnType("longtext");

                    b.Property<string>("UrlConstancia")
                        .HasColumnType("longtext");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("char(36)");

                    b.HasKey("IdLicencias");

                    b.HasIndex("IdColaborador");

                    b.HasIndex("IdEstadoLicencia");

                    b.HasIndex("IdTipoLicencia");

                    b.HasIndex("Uuid")
                        .IsUnique();

                    b.ToTable("RHLicencias", (string)null);
                });

            modelBuilder.Entity("rrhh_backend.Data.Models.RHTipoLicencias", b =>
                {
                    b.Property<int>("IdTipoLicencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoLicencia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdTipoLicencia");

                    b.ToTable("RHTipoLicencias", (string)null);
                });

            modelBuilder.Entity("rrhh_backend.Data.Models.AdminBitacoraUsuario", b =>
                {
                    b.HasOne("rrhh_backend.Data.Models.AdminUser", "IdUsuarioNavigation")
                        .WithMany("UserBitacoraUsuarios")
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("Relationship3");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("rrhh_backend.Data.Models.AdminResetPassword", b =>
                {
                    b.HasOne("rrhh_backend.Data.Models.AdminUser", "IdUsuarioNavigation")
                        .WithMany("UserResetPasswords")
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("Relationship2");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("rrhh_backend.Data.Models.AdminRolesPermiso", b =>
                {
                    b.HasOne("rrhh_backend.Data.Models.AdminPermiso", "IdPermisoNavigation")
                        .WithMany("UserRolesPermisos")
                        .HasForeignKey("IdPermiso")
                        .IsRequired()
                        .HasConstraintName("Relationship5");

                    b.HasOne("rrhh_backend.Data.Models.AdminRole", "IdRoleNavigation")
                        .WithMany("UserRolesPermisos")
                        .HasForeignKey("IdRole")
                        .IsRequired()
                        .HasConstraintName("Relationship4");

                    b.Navigation("IdPermisoNavigation");

                    b.Navigation("IdRoleNavigation");
                });

            modelBuilder.Entity("rrhh_backend.Data.Models.AdminUser", b =>
                {
                    b.HasOne("rrhh_backend.Data.Models.RHColaborador", "IdColaboradorNavigation")
                        .WithOne("UserUser")
                        .HasForeignKey("rrhh_backend.Data.Models.AdminUser", "IdColaborador")
                        .HasConstraintName("FK_User_User_Gth_Colaborador");

                    b.HasOne("rrhh_backend.Data.Models.AdminEstado", "IdEstadoNavigation")
                        .WithMany("UserUsers")
                        .HasForeignKey("IdEstado")
                        .HasConstraintName("Relationship1");

                    b.Navigation("IdColaboradorNavigation");

                    b.Navigation("IdEstadoNavigation");
                });

            modelBuilder.Entity("rrhh_backend.Data.Models.AdminUserRole", b =>
                {
                    b.HasOne("rrhh_backend.Data.Models.AdminRole", "IdRoleNavigation")
                        .WithMany("UserUserRoles")
                        .HasForeignKey("IdRole")
                        .IsRequired()
                        .HasConstraintName("Relationship8");

                    b.HasOne("rrhh_backend.Data.Models.AdminUser", "IdUsuarioNavigation")
                        .WithMany("UserUserRoles")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("Relationship7");

                    b.Navigation("IdRoleNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("rrhh_backend.Data.Models.RHColaborador", b =>
                {
                    b.HasOne("rrhh_backend.Data.Models.RHDepartamento", "RHDepartamento")
                        .WithMany("RHColaboradores")
                        .HasForeignKey("IdDepartamento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("rrhh_backend.Data.Models.RHEstadoCivil", "RHEstadoCivil")
                        .WithMany("RHColaboradores")
                        .HasForeignKey("IdEstadoCivil")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RHColaborador_RHEstadoCivil");

                    b.HasOne("rrhh_backend.Data.Models.RHEstadoColaborador", "RHEstadoColaborador")
                        .WithMany("RHColaboradores")
                        .HasForeignKey("IdEstadoColaborador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RHColaborador_RHEstadoColaborador");

                    b.Navigation("RHDepartamento");

                    b.Navigation("RHEstadoCivil");

                    b.Navigation("RHEstadoColaborador");
                });

            modelBuilder.Entity("rrhh_backend.Data.Models.RHHistorialDepartamento", b =>
                {
                    b.HasOne("rrhh_backend.Data.Models.RHColaborador", "RHColaborador")
                        .WithMany("RHHistorialDepartamentos")
                        .HasForeignKey("IdColaborador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RHHistorialDepartamento_RHColaborador");

                    b.HasOne("rrhh_backend.Data.Models.RHDepartamento", "RHDepartamento")
                        .WithMany("RHHistorialDepartamentos")
                        .HasForeignKey("IdDepartamento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RHHistorialDepartamento_RHDepartamento");

                    b.Navigation("RHColaborador");

                    b.Navigation("RHDepartamento");
                });

            modelBuilder.Entity("rrhh_backend.Data.Models.RHLicencias", b =>
                {
                    b.HasOne("rrhh_backend.Data.Models.RHColaborador", "RHColaborador")
                        .WithMany("RHLicencias")
                        .HasForeignKey("IdColaborador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("rrhh_backend.Data.Models.RHEstadoLicencias", "RHEstadoLicencias")
                        .WithMany("RHLicencias")
                        .HasForeignKey("IdEstadoLicencia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("rrhh_backend.Data.Models.RHTipoLicencias", "RHTipoLicencias")
                        .WithMany("RHLicencias")
                        .HasForeignKey("IdTipoLicencia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RHColaborador");

                    b.Navigation("RHEstadoLicencias");

                    b.Navigation("RHTipoLicencias");
                });

            modelBuilder.Entity("rrhh_backend.Data.Models.AdminEstado", b =>
                {
                    b.Navigation("UserUsers");
                });

            modelBuilder.Entity("rrhh_backend.Data.Models.AdminPermiso", b =>
                {
                    b.Navigation("UserRolesPermisos");
                });

            modelBuilder.Entity("rrhh_backend.Data.Models.AdminRole", b =>
                {
                    b.Navigation("UserRolesPermisos");

                    b.Navigation("UserUserRoles");
                });

            modelBuilder.Entity("rrhh_backend.Data.Models.AdminUser", b =>
                {
                    b.Navigation("UserBitacoraUsuarios");

                    b.Navigation("UserResetPasswords");

                    b.Navigation("UserUserRoles");
                });

            modelBuilder.Entity("rrhh_backend.Data.Models.RHColaborador", b =>
                {
                    b.Navigation("RHHistorialDepartamentos");

                    b.Navigation("RHLicencias");

                    b.Navigation("UserUser");
                });

            modelBuilder.Entity("rrhh_backend.Data.Models.RHDepartamento", b =>
                {
                    b.Navigation("RHColaboradores");

                    b.Navigation("RHHistorialDepartamentos");
                });

            modelBuilder.Entity("rrhh_backend.Data.Models.RHEstadoCivil", b =>
                {
                    b.Navigation("RHColaboradores");
                });

            modelBuilder.Entity("rrhh_backend.Data.Models.RHEstadoColaborador", b =>
                {
                    b.Navigation("RHColaboradores");
                });

            modelBuilder.Entity("rrhh_backend.Data.Models.RHEstadoLicencias", b =>
                {
                    b.Navigation("RHLicencias");
                });

            modelBuilder.Entity("rrhh_backend.Data.Models.RHTipoLicencias", b =>
                {
                    b.Navigation("RHLicencias");
                });
#pragma warning restore 612, 618
        }
    }
}
